"""added studentcoursemapping model

Revision ID: 513f7ee58e7b
Revises: 5e65d4b19431
Create Date: 2023-05-03 11:17:34.067013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '513f7ee58e7b'
down_revision = '5e65d4b19431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_mapping',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_course_mapping')
    # ### end Alembic commands ###
