"""solved error of back_populates

Revision ID: 5e65d4b19431
Revises: d4df7dd4f71c
Create Date: 2023-05-02 16:16:12.782978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e65d4b19431'
down_revision = 'd4df7dd4f71c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
