"""Added Reset Code Model

Revision ID: 7d58015de196
Revises: a131e19c33d9
Create Date: 2023-05-04 11:37:31.908104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d58015de196'
down_revision = 'a131e19c33d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reset_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('reset_code', sa.String(length=50), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_reset_codes_id'), 'reset_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reset_codes_id'), table_name='reset_codes')
    op.drop_table('reset_codes')
    # ### end Alembic commands ###
