"""

Revision ID: a131e19c33d9
Revises: 513f7ee58e7b
Create Date: 2023-05-03 11:39:45.689958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a131e19c33d9'
down_revision = '513f7ee58e7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
