"""change user_type field

Revision ID: aa3ca3f2dea6
Revises: c2fafd00587f
Create Date: 2023-04-26 18:10:06.248939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3ca3f2dea6'
down_revision = 'c2fafd00587f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
